name: CD - Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar SDK do .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar projeto
        run: dotnet build --no-restore --configuration Release

      - name: Publicar projeto
        run: dotnet publish -c Release -o ./publish

      # Exemplo: subir artefato publicado
      - name: Upload Artefato
        uses: actions/upload-artifact@v3
        with:
          name: aplicacao-publicada
          path: ./publish
